on:
  push:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
    - name: Run CI
      run: |
        docker run -d -p 5000:5000 --restart always --name registry registry:2
        sleep 3
        go run .
        docker pull localhost:5000/test